package com.oop.demo;

public class Assignment1 {
	// DECLARE A CLASS CALLED AS POSMACHINE
	// DECLARE PROPERTIES
	// DECLARE AN ARRAY CONTAINING LIST OF ITEMS BILLED
	// DECLARE ANOTHER ARRAY CONTAINING PRICES OF ITEMS
	// DECLARE A METHOD CALLED AS GENERATEBILL
	// GENERATEBILL SHOULD GIVE YOU A FORMATER PRINT OF TOTAL BILL AMOUNT AND 
	// PRICE FOR EACH ITEM INTO CONSOLE
	// IF BILL > 10000 - 5% - PRINT REWARD POINTS - 1 point for every 100/-
	// IF BILL > 20000 - 7% - PRINT REWARD POINTS - 1 point for every 100/-
	// IF BILL > 30000 - 10% - PRINT REWARD POINTS - 1 point for every 100/-
	// 
}
