package com.corejava.collections.list;

public class Assignment0430 {
	// CREATE A CLASS CALLED AS PERSON
	// CREATE A SUB-CLASS CALLED AS DOCTOR
	// CREATE ANOTHER SUB-CLASS CALLED AS PATIENT
	// CREATE A CLASS CALLED AS HOSPITAL
	// CREATE LIST OF MEDICINES PRESCRIBED BY DOCTOR FOR A PATIENT
	// DESIGN A MENU IN HOSPITAL CLASS
	// MENU OPTIONS
	// INPUT PATIENT DETAILS
	// MODIFY PRESCRIPTION 
	// DELETE PATIENT
}
